// REQ: REQ-UI-005, REQ-UI-006, REQ-UI-007, REQ-ALP-014, REQ-NOT-006,
// REQ-STR-009, REQ-LLM-006, REQ-EXE-007

export const ALLOWED_CONFIG_PATHS = [
  "default_selected_venue",
  "live_enabled",
  "venues.polymarket_us.enabled",
  "venues.polymarket_international.enabled",
  "venues.alpaca.enabled",
  "trading_loop_interval_seconds",
  "strategies.arbitrage.enabled",
  "strategies.convergence.enabled",
  "strategies.whale_copy.enabled",
  "llm.openai.budget_usd",
  "llm.openai.settings.model",
  "llm.claude.budget_usd",
  "reasoning.max_prompts_per_provider_per_run",
  "reasoning.polymarket.prompt_version",
  "reasoning.polymarket.min_confidence",
  "reasoning.polymarket.min_edge",
  "reasoning.polymarket.checks",
  "reasoning.alpaca.prompt_version",
  "reasoning.alpaca.min_confidence",
  "reasoning.alpaca.min_edge",
  "reasoning.alpaca.inputs",
  "risk.polymarket.max_position_usd",
  "risk.polymarket.max_daily_loss_usd",
  "risk.polymarket.max_open_positions",
  "risk.polymarket.market_order_slippage_threshold",
  "risk.alpaca.max_position_usd",
  "risk.alpaca.max_daily_loss_usd",
  "risk.alpaca.max_open_positions",
  "risk.alpaca.max_portfolio_allocation_per_symbol",
  "risk.alpaca.market_order_slippage_threshold",
  "exit.alpaca.profit_target_pct",
  "exit.alpaca.stop_loss_pct",
  "exit.alpaca.trailing_stop_pct",
  "exit.alpaca.max_position_age_hours",
  "exit.alpaca.market_hours_only",
  "exit.alpaca.close_before_market_close_minutes",
  "scanner.polymarket.market_data_limit",
  "scanner.polymarket.min_depth",
  "scanner.polymarket.min_liquidity",
  "scanner.polymarket.max_spread",
  "scanner.polymarket.min_volume",
  "scanner.polymarket.min_hours_to_resolution",
  "scanner.polymarket.max_hours_to_resolution",
  "scanner.polymarket.allowed_categories",
  "scanner.polymarket.blocked_categories",
  "scanner.alpaca.min_quote_liquidity",
  "scanner.alpaca.max_spread",
  "scanner.alpaca.min_history_bars",
  "scanner.alpaca.strategies.momentum.enabled",
  "scanner.alpaca.strategies.momentum.min_change_pct",
  "scanner.alpaca.strategies.mean_reversion.enabled",
  "scanner.alpaca.strategies.mean_reversion.min_deviation_pct",
  "scanner.alpaca.strategies.gap.enabled",
  "scanner.alpaca.strategies.gap.min_gap_pct",
  "scanner.alpaca.strategies.liquidity.enabled",
  "scanner.alpaca.strategies.liquidity.min_volume",
  "scanner.alpaca.strategies.volatility.enabled",
  "scanner.alpaca.strategies.volatility.min_range_pct",
  "scanner.alpaca.strategies.unusual_volume.enabled",
  "scanner.alpaca.strategies.unusual_volume.min_ratio",
  "alpaca.account_mode",
  "alpaca.symbol_presets",
  "alpaca.custom_symbols",
  "alpaca.custom_presets",
  "alpaca.symbol_universe",
  "alpaca.preset_refresh.enabled",
  "alpaca.preset_refresh.cadence_hours",
  "alpaca.preset_refresh.stale_after_hours",
  "alpaca.preset_refresh.sources",
  "notifications.recipients",
  "notifications.thresholds.daily_loss_usd",
  "notifications.thresholds.model_spend_usd",
  "notifications.thresholds.venue_degradation_minutes",
  "notifications.cooldown_seconds",
  "notifications.digest_schedule_utc",
  "notifications.email_on_trade_placed",
] as const;

export type AllowedConfigPath = (typeof ALLOWED_CONFIG_PATHS)[number];

export function isAllowedConfigPath(path: string): path is AllowedConfigPath {
  return ALLOWED_CONFIG_PATHS.includes(path as AllowedConfigPath);
}

export type ConfigPathDetail = {
  label: string;
  description: string;
  valueHint: string;
  effect: string;
};

export const CONFIG_PATH_DETAILS: Record<AllowedConfigPath, ConfigPathDetail> = {
  default_selected_venue: {
    label: "Default venue",
    description: "Chooses the primary venue the bot evaluates first.",
    valueHint: "polymarket_us, polymarket_international, or alpaca",
    effect: "Applies on the next loop.",
  },
  live_enabled: {
    label: "Live trading",
    description: "Controls whether approved orders may be submitted to a live venue.",
    valueHint: "true or false",
    effect: "Keep false until dry-run evidence and operator signoff are complete.",
  },
  "venues.polymarket_us.enabled": {
    label: "Polymarket US venue",
    description: "Allows scanning, scoring, and trading for Polymarket US when other gates pass.",
    valueHint: "true or false",
    effect: "A disabled venue will not scan, score, or trade.",
  },
  "venues.polymarket_international.enabled": {
    label: "Polymarket International venue",
    description: "Allows international Polymarket activity when the environment supports it.",
    valueHint: "true or false",
    effect: "Unsupported venue settings still block live orders.",
  },
  "venues.alpaca.enabled": {
    label: "Alpaca venue",
    description: "Allows stock and ETF evaluation through Alpaca when account checks pass.",
    valueHint: "true or false",
    effect: "Alpaca remains long-only for stocks and ETFs.",
  },
  trading_loop_interval_seconds: {
    label: "Trading loop interval",
    description: "Sets how often the backend should run the trading loop.",
    valueHint: "Number of seconds, minimum 5",
    effect: "Shorter intervals can increase API and model usage.",
  },
  "strategies.arbitrage.enabled": {
    label: "Arbitrage strategy",
    description: "Enables related-market dislocation signals.",
    valueHint: "true or false",
    effect: "Signals still need consensus and risk approval.",
  },
  "strategies.convergence.enabled": {
    label: "Convergence strategy",
    description: "Enables signals where model probability diverges from market price.",
    valueHint: "true or false",
    effect: "Signals still need consensus and risk approval.",
  },
  "strategies.whale_copy.enabled": {
    label: "Whale-copy strategy",
    description: "Enables target-wallet follow signals after the configured delay.",
    valueHint: "true or false",
    effect: "The strategy needs wallet target data before it produces signals.",
  },
  "llm.openai.budget_usd": {
    label: "OpenAI budget",
    description: "Caps OpenAI model spend for scoring over a rolling 24-hour window.",
    valueHint: "Positive dollar value, such as 20.00",
    effect: "The bot resumes OpenAI scoring as older usage leaves the 24-hour window.",
  },
  "llm.openai.settings.model": {
    label: "OpenAI scoring model",
    description: "Chooses the OpenAI model used when scoring scanner survivors.",
    valueHint: "gpt-5-mini or gpt-5-nano",
    effect: "Applies to the next reasoning call. Use nano for the lowest cost or mini when scoring quality matters more.",
  },
  "llm.claude.budget_usd": {
    label: "Claude budget",
    description: "Caps Claude model spend for scoring over a rolling 24-hour window.",
    valueHint: "Positive dollar value, such as 20.00",
    effect: "The bot resumes Claude scoring as older usage leaves the 24-hour window.",
  },
  "reasoning.max_prompts_per_provider_per_run": {
    label: "Reasoning prompt cap",
    description: "Maximum prompts one model provider can receive in one run.",
    valueHint: "Positive whole number, such as 4",
    effect: "Extra scanner survivors are skipped before a provider call.",
  },
  "reasoning.polymarket.prompt_version": {
    label: "Polymarket prompt",
    description: "Prompt version used for Polymarket reasoning checks.",
    valueHint: "Text, such as pm-brain-v1",
    effect: "Applies to the next scanner survivor sent to reasoning.",
  },
  "reasoning.polymarket.min_confidence": {
    label: "Polymarket confidence",
    description: "Minimum model confidence expected before downstream strategy consensus.",
    valueHint: "Ratio, such as 0.75",
    effect: "Recorded with each reasoning prompt and used by later strategy gates.",
  },
  "reasoning.polymarket.min_edge": {
    label: "Polymarket edge",
    description: "Minimum probability gap required for a directional Polymarket signal.",
    valueHint: "Ratio, such as 0.07",
    effect: "Smaller gaps are normalized to hold.",
  },
  "reasoning.polymarket.checks": {
    label: "Polymarket checks",
    description: "Checks included in Polymarket reasoning prompts.",
    valueHint: "JSON array, such as [\"base_rate\", \"news\", \"whale_check\", \"disposition\"]",
    effect: "Changes the requested brain checks for future prompts.",
  },
  "reasoning.alpaca.prompt_version": {
    label: "Stock prompt",
    description: "Prompt version used for Alpaca stock reasoning.",
    valueHint: "Text, such as stock-brain-v1",
    effect: "Applies to the next stock candidate sent to reasoning.",
  },
  "reasoning.alpaca.min_confidence": {
    label: "Stock confidence",
    description: "Minimum model confidence expected before downstream stock consensus.",
    valueHint: "Ratio, such as 0.60",
    effect: "Recorded with each stock reasoning prompt and used by later strategy gates.",
  },
  "reasoning.alpaca.min_edge": {
    label: "Stock edge",
    description: "Minimum probability gap required for a directional stock signal.",
    valueHint: "Ratio, such as 0.02",
    effect: "Smaller gaps are normalized to neutral.",
  },
  "reasoning.alpaca.inputs": {
    label: "Stock inputs",
    description: "Inputs included in stock reasoning prompts.",
    valueHint: "JSON array of stock input names",
    effect: "Changes the context requested from the model for future stock prompts.",
  },
  "risk.polymarket.max_position_usd": {
    label: "Polymarket max position",
    description: "Maximum Polymarket exposure for one position.",
    valueHint: "Positive dollar value",
    effect: "Orders above the limit are refused.",
  },
  "risk.polymarket.max_daily_loss_usd": {
    label: "Polymarket daily loss limit",
    description: "Maximum daily loss allowed before Polymarket orders are refused.",
    valueHint: "Positive dollar value",
    effect: "The risk gate blocks new orders at or above this loss.",
  },
  "risk.polymarket.max_open_positions": {
    label: "Polymarket open positions",
    description: "Maximum number of open Polymarket positions per model provider.",
    valueHint: "Positive whole number",
    effect: "The risk gate blocks new positions above the limit.",
  },
  "risk.polymarket.market_order_slippage_threshold": {
    label: "Polymarket slippage limit",
    description: "Maximum estimated slippage allowed for Polymarket market orders.",
    valueHint: "Ratio, such as 0.02 for 2 percent",
    effect: "Market orders above the threshold are refused.",
  },
  "risk.alpaca.max_position_usd": {
    label: "Alpaca max position",
    description: "Maximum stock or ETF exposure for one order.",
    valueHint: "Positive dollar value",
    effect: "Orders above the limit are refused.",
  },
  "risk.alpaca.max_daily_loss_usd": {
    label: "Alpaca daily loss limit",
    description: "Maximum daily loss allowed before Alpaca orders are refused.",
    valueHint: "Positive dollar value",
    effect: "The risk gate blocks new Alpaca orders at or above this loss.",
  },
  "risk.alpaca.max_open_positions": {
    label: "Alpaca open positions",
    description: "Maximum number of open stock or ETF positions across the active Alpaca account.",
    valueHint: "Positive whole number",
    effect: "The risk gate blocks new positions above the limit.",
  },
  "risk.alpaca.max_portfolio_allocation_per_symbol": {
    label: "Alpaca symbol allocation",
    description: "Maximum share of model capital allocated to one Alpaca symbol.",
    valueHint: "Ratio, such as 0.10 for 10 percent",
    effect: "Orders above the allocation limit are refused.",
  },
  "risk.alpaca.market_order_slippage_threshold": {
    label: "Alpaca slippage limit",
    description: "Maximum estimated slippage allowed for Alpaca market orders.",
    valueHint: "Ratio, such as 0.005 for 0.5 percent",
    effect: "Market orders above the threshold are refused.",
  },
  "exit.alpaca.profit_target_pct": {
    label: "Stock profit target",
    description: "Closes a stock position when its gain reaches this percentage.",
    valueHint: "Ratio, such as 0.02 for 2 percent",
    effect: "The exit monitor checks this target on every trading loop.",
  },
  "exit.alpaca.stop_loss_pct": {
    label: "Stock stop loss",
    description: "Closes a stock position when its loss reaches this percentage.",
    valueHint: "Ratio, such as 0.01 for 1 percent",
    effect: "The exit monitor checks this loss limit on every trading loop.",
  },
  "exit.alpaca.trailing_stop_pct": {
    label: "Stock trailing stop",
    description: "Closes a profitable position after it falls this percentage from its recorded high.",
    valueHint: "Ratio, such as 0.01 for 1 percent",
    effect: "The trailing stop applies when a high-water mark is available.",
  },
  "exit.alpaca.max_position_age_hours": {
    label: "Stock maximum hold",
    description: "Marks a stock position stale after this many hours.",
    valueHint: "Positive hours, such as 6",
    effect: "A stale position can exit when its minimum movement rule is also met.",
  },
  "exit.alpaca.market_hours_only": {
    label: "Regular-hours stock trading",
    description: "Restricts new stock entries and exit submissions to the regular market session.",
    valueHint: "true or false",
    effect: "When enabled, the bot does not queue new stock orders outside regular hours.",
  },
  "exit.alpaca.close_before_market_close_minutes": {
    label: "Close stocks before market close",
    description: "Closes stock positions this many minutes before the regular session ends.",
    valueHint: "Whole minutes from 1 to 120",
    effect: "New stock entries are also blocked during the close window.",
  },
  "scanner.polymarket.market_data_limit": {
    label: "Polymarket candidates",
    description: "Maximum active Polymarket priced candidates fetched before scanner filters run.",
    valueHint: "Whole number from 1 to 250",
    effect: "Higher values increase Gamma and CLOB API calls on the next market-data pull.",
  },
  "scanner.polymarket.min_depth": {
    label: "Polymarket min depth",
    description: "Minimum order-book size required on each side of a Polymarket candidate.",
    valueHint: "Positive number, such as 500",
    effect: "Candidates below this bid or ask depth are rejected in the scanner.",
  },
  "scanner.polymarket.min_liquidity": {
    label: "Polymarket min liquidity",
    description: "Minimum combined order-book liquidity for a Polymarket candidate.",
    valueHint: "Positive number, such as 500",
    effect: "Lower-liquidity markets are rejected before reasoning.",
  },
  "scanner.polymarket.max_spread": {
    label: "Polymarket max spread",
    description: "Maximum allowed bid/ask spread for a Polymarket candidate.",
    valueHint: "Ratio, such as 0.05",
    effect: "Wide-spread markets are rejected before reasoning.",
  },
  "scanner.polymarket.min_volume": {
    label: "Polymarket min volume",
    description: "Minimum Gamma market volume required for scanner acceptance.",
    valueHint: "Positive number",
    effect: "Markets below the threshold are rejected.",
  },
  "scanner.polymarket.min_hours_to_resolution": {
    label: "Polymarket min hours",
    description: "Minimum hours remaining before market resolution.",
    valueHint: "Positive number, such as 4",
    effect: "Markets too close to resolution are rejected.",
  },
  "scanner.polymarket.max_hours_to_resolution": {
    label: "Polymarket max hours",
    description: "Maximum hours remaining before market resolution.",
    valueHint: "Positive number, such as 168",
    effect: "Markets tying capital too long are rejected.",
  },
  "scanner.polymarket.allowed_categories": {
    label: "Polymarket categories",
    description: "Optional category allowlist for Polymarket scanning.",
    valueHint: "JSON array, such as [\"Politics\", \"Crypto\"]",
    effect: "When set, only these categories pass scanner filters.",
  },
  "scanner.polymarket.blocked_categories": {
    label: "Polymarket blocked categories",
    description: "Optional category blocklist for Polymarket scanning.",
    valueHint: "JSON array, such as [\"Sports\"]",
    effect: "Matching categories are rejected.",
  },
  "scanner.alpaca.min_quote_liquidity": {
    label: "Stock quote liquidity",
    description: "Minimum bid plus ask size required for stock scanner input.",
    valueHint: "Positive number, such as 0.5",
    effect: "Thin quotes are rejected before stock strategy checks.",
  },
  "scanner.alpaca.max_spread": {
    label: "Stock max spread",
    description: "Maximum dollar spread allowed for stock scanner input.",
    valueHint: "Positive number, such as 1.00",
    effect: "Wide-spread symbols are rejected before strategy checks.",
  },
  "scanner.alpaca.min_history_bars": {
    label: "Stock history bars",
    description: "Minimum daily bars required before stock strategy checks run.",
    valueHint: "Positive whole number, such as 2",
    effect: "Symbols without enough history are rejected.",
  },
  "scanner.alpaca.strategies.momentum.enabled": {
    label: "Momentum scanner",
    description: "Enables the stock momentum scanner strategy.",
    valueHint: "true or false",
    effect: "Disabled strategy matches are ignored.",
  },
  "scanner.alpaca.strategies.momentum.min_change_pct": {
    label: "Momentum threshold",
    description: "Minimum positive price change for momentum acceptance.",
    valueHint: "Ratio, such as 0.01",
    effect: "Higher values reduce momentum candidates.",
  },
  "scanner.alpaca.strategies.mean_reversion.enabled": {
    label: "Mean reversion scanner",
    description: "Enables the stock mean-reversion scanner strategy.",
    valueHint: "true or false",
    effect: "Disabled strategy matches are ignored.",
  },
  "scanner.alpaca.strategies.mean_reversion.min_deviation_pct": {
    label: "Mean reversion threshold",
    description: "Minimum price deviation from the moving average.",
    valueHint: "Ratio, such as 0.02",
    effect: "Higher values reduce mean-reversion candidates.",
  },
  "scanner.alpaca.strategies.gap.enabled": {
    label: "Gap scanner",
    description: "Enables the stock gap scanner strategy.",
    valueHint: "true or false",
    effect: "Disabled strategy matches are ignored.",
  },
  "scanner.alpaca.strategies.gap.min_gap_pct": {
    label: "Gap threshold",
    description: "Minimum open-to-prior-close gap for scanner acceptance.",
    valueHint: "Ratio, such as 0.015",
    effect: "Higher values reduce gap candidates.",
  },
  "scanner.alpaca.strategies.liquidity.enabled": {
    label: "Liquidity scanner",
    description: "Enables the stock liquidity scanner strategy.",
    valueHint: "true or false",
    effect: "Disabled strategy matches are ignored.",
  },
  "scanner.alpaca.strategies.liquidity.min_volume": {
    label: "Liquidity threshold",
    description: "Minimum daily volume for the liquidity scanner.",
    valueHint: "Positive number, such as 100000",
    effect: "Higher values reduce liquidity candidates.",
  },
  "scanner.alpaca.strategies.volatility.enabled": {
    label: "Volatility scanner",
    description: "Enables the stock volatility scanner strategy.",
    valueHint: "true or false",
    effect: "Disabled strategy matches are ignored.",
  },
  "scanner.alpaca.strategies.volatility.min_range_pct": {
    label: "Volatility threshold",
    description: "Minimum high-low range as a share of close.",
    valueHint: "Ratio, such as 0.02",
    effect: "Higher values reduce volatility candidates.",
  },
  "scanner.alpaca.strategies.unusual_volume.enabled": {
    label: "Unusual volume scanner",
    description: "Enables the stock unusual-volume scanner strategy.",
    valueHint: "true or false",
    effect: "Disabled strategy matches are ignored.",
  },
  "scanner.alpaca.strategies.unusual_volume.min_ratio": {
    label: "Unusual volume threshold",
    description: "Minimum latest-volume to average-volume ratio.",
    valueHint: "Positive number, such as 1.50",
    effect: "Higher values reduce unusual-volume candidates.",
  },
  "alpaca.account_mode": {
    label: "Alpaca account mode",
    description: "Selects Alpaca paper or live account mode.",
    valueHint: "paper or live",
    effect: "Live mode also requires credentials, reconciliation, and risk approval.",
  },
  "alpaca.symbol_presets": {
    label: "Alpaca stock presets",
    description: "Selects built-in or user-defined symbol groups for Alpaca scanning.",
    valueHint: "JSON array, such as [\"sp500\", \"nasdaq100\"]",
    effect: "Preset symbols are resolved on the next loop and combined with custom symbols.",
  },
  "alpaca.custom_symbols": {
    label: "Alpaca extra symbols",
    description: "Adds one-off tickers, such as a new IPO, without replacing selected presets.",
    valueHint: "JSON array, such as [\"CRCL\", \"FIG\"]",
    effect: "Symbols are added to the resolved Alpaca universe on the next loop.",
  },
  "alpaca.custom_presets": {
    label: "Alpaca custom presets",
    description: "Defines reusable operator-managed symbol groups.",
    valueHint: "JSON object, such as {\"new_ipos\":[\"CRCL\", \"FIG\"]}",
    effect: "Custom preset names can be added to Alpaca stock presets.",
  },
  "alpaca.symbol_universe": {
    label: "Alpaca resolved universe",
    description: "Resolved stock universe used by Alpaca ingestion. Prefer presets and extra symbols for edits.",
    valueHint: "JSON array of resolved symbols",
    effect: "This is retained for legacy overrides and backend visibility.",
  },
  "alpaca.preset_refresh.enabled": {
    label: "Preset refresh",
    description: "Controls scheduled refresh of built-in Alpaca preset memberships.",
    valueHint: "true or false",
    effect: "When enabled, scheduled runs refresh due preset snapshots before Alpaca pulls.",
  },
  "alpaca.preset_refresh.cadence_hours": {
    label: "Preset refresh cadence",
    description: "Minimum hours between refresh attempts for each stock preset.",
    valueHint: "Positive whole number, such as 24",
    effect: "Lower values refresh more often and can increase source requests.",
  },
  "alpaca.preset_refresh.stale_after_hours": {
    label: "Preset stale age",
    description: "Age threshold used to show when preset membership is stale.",
    valueHint: "Positive whole number, such as 168",
    effect: "The dashboard uses this to flag old preset membership data.",
  },
  "alpaca.preset_refresh.sources": {
    label: "Preset sources",
    description: "Source URL mapping used by scheduled preset refresh.",
    valueHint: "{\"sp500\":\"https://...\",\"nasdaq100\":\"https://...\"}",
    effect: "Changes where future scheduled refreshes load preset membership.",
  },
  "notifications.recipients": {
    label: "Notification recipients",
    description: "Controls who receives alerts and daily digests.",
    valueHint: "JSON object, such as {\"operator\":\"name@example.com\"}",
    effect: "Recipients must be valid email addresses.",
  },
  "notifications.thresholds.daily_loss_usd": {
    label: "Daily loss alert",
    description: "Sends an alert when daily P&L crosses the configured loss threshold.",
    valueHint: "Positive dollar value",
    effect: "Alerts still follow cooldown rules.",
  },
  "notifications.thresholds.model_spend_usd": {
    label: "Model spend alert",
    description: "Sends an alert when model spend crosses the configured threshold.",
    valueHint: "Positive dollar value",
    effect: "Alerts still follow cooldown rules.",
  },
  "notifications.thresholds.venue_degradation_minutes": {
    label: "Venue degradation alert",
    description: "Sends an alert when a venue remains degraded for the configured period.",
    valueHint: "Positive number of minutes",
    effect: "Alerts still follow cooldown rules.",
  },
  "notifications.cooldown_seconds": {
    label: "Alert cooldown",
    description: "Minimum time between repeated alerts for the same condition.",
    valueHint: "Positive number of seconds",
    effect: "Prevents repeated alert delivery.",
  },
  "notifications.digest_schedule_utc": {
    label: "Digest schedule",
    description: "UTC time for the daily summary email.",
    valueHint: "HH:MM, such as 13:00",
    effect: "Uses UTC, not local workstation time.",
  },
  "notifications.email_on_trade_placed": {
    label: "Email trade alerts",
    description: "Sends an email when an actual live order is submitted.",
    valueHint: "true or false",
    effect: "Simulated and refused orders do not trigger this alert.",
  },
};
