"""Service layer exports.

REQ: REQ-OBS-001, REQ-OBS-002, REQ-OBS-003, REQ-OBS-004, REQ-OBS-005,
REQ-OBS-006, REQ-UI-002, REQ-UI-003, REQ-UI-006, REQ-EXE-016,
REQ-ALP-005, REQ-ALP-006, REQ-ALP-007, REQ-ALP-009,
REQ-ALP-010, REQ-ALP-011, REQ-ALP-012, REQ-DAT-001,
REQ-DAT-002, REQ-DAT-005, REQ-DAT-008, REQ-WAL-001,
REQ-WAL-002, REQ-WAL-004, REQ-WAL-005, REQ-WAL-006,
REQ-LLM-001, REQ-LLM-002, REQ-LLM-003, REQ-LLM-004, REQ-LLM-005,
REQ-EXE-002, REQ-EXE-004, REQ-EXE-005, REQ-EXE-006,
REQ-EXE-009, REQ-EXE-013, REQ-EXE-014, REQ-EXE-015,
REQ-EXE-017, REQ-NOT-002, REQ-NOT-003, REQ-NOT-004,
REQ-NOT-005, REQ-CMP-002, REQ-CMP-004, REQ-EXT-002,
REQ-EXT-003, REQ-EXT-004, REQ-EXT-005, REQ-EXT-006,
REQ-UI-001, REQ-UI-004, REQ-UI-009, REQ-UI-010, REQ-UI-011,
REQ-DEP-005
"""

from app.services.auth_service import AuthService, DashboardAccessResult, MutationContextResult
from app.services.audit_service import (
    ActorContext,
    AuditService,
    CloudWatchLogSink,
    ConfigChange,
    ConfigMutationResult,
    LogEmissionResult,
    ObservabilitySnapshot,
)
from app.services.config_service import (
    ConfigAuthorizationError,
    ConfigConflictError,
    ConfigPatchOperation,
    ConfigReloadResult,
    ConfigSaveResult,
    ConfigService,
    ConfigValidationError,
    DEFAULT_ALPACA_SYMBOL_UNIVERSE,
    RuntimeConfigSnapshot,
    default_config_payload,
)
from app.services.comparison_service import (
    ComparisonGroup,
    ComparisonSummary,
    PerformanceRecord,
    compare_model_performance,
    mark_comparison_metric_unavailable,
)
from app.services.control_service import KillSwitchActivationResult, KillSwitchService, KillSwitchState
from app.services.dashboard_service import (
    ComparisonDashboardView,
    DashboardShellResult,
    DashboardStatusResult,
    ModelProviderSummary,
    build_comparison_dashboard_view,
    build_dashboard_shell,
    build_dashboard_status,
    build_model_provider_summary,
    render_wallet_dashboard_status,
)
from app.services.execution_service import (
    AlpacaExecutionRequest,
    AlpacaExecutionResult,
    DryRunOrderRequest,
    ExecutionResult,
    FakeAlpacaVenueSubmitter,
    FakeCancelVenue,
    FakeVenueSubmitter,
    KillSwitchCancelResult,
    OpenOrder,
    PolymarketExecutionRequest,
    cancel_open_orders_for_kill_switch,
    execute_dry_run_order,
    execute_alpaca_order,
    execute_polymarket_order,
    resolve_alpaca_account_mode,
)
from app.services.exit_service import (
    ExitExecutionRequest,
    ExitExecutionResult,
    evaluate_profit_target_exit,
    evaluate_stale_thesis_exit,
    evaluate_volume_spike_exit,
    execute_exit_order,
)
from app.services.ingestion_service import (
    DataFreshnessStatus,
    FakeSnapshotSource,
    IngestionCheckpoint,
    IngestionRunResult,
    IngestionService,
    check_market_data_freshness,
)
from app.services.market_data_provider import (
    MarketDataProviderResult,
    ProviderBackedMarketDataFetcher,
)
from app.services.scanner_service import (
    DEFAULT_SCANNER_CONFIG,
    ScannerRunResult,
    ScannerService,
    scanner_config_from_payload,
    scanner_run_payload,
)
from app.services.stock_universe import (
    BUILT_IN_ALPACA_PRESETS,
    DEFAULT_ALPACA_SYMBOL_PRESETS,
    normalize_symbol_list,
    resolve_alpaca_symbol_universe,
)
from app.services.stock_history_service import (
    ALPACA_BROKER_HISTORY_SOURCE_PREFIX,
    ALPACA_DATA_BASE_URL,
    ALPACA_LIVE_TRADING_BASE_URL,
    ALPACA_PAPER_TRADING_BASE_URL,
    ALPACA_STOCK_BARS_SOURCE_PREFIX,
    AlpacaBrokerHistoryBackfiller,
    AlpacaHistoricalImportSummary,
    AlpacaHistoryImportError,
    AlpacaStockHistoryImporter,
)
from app.services.llm_service import (
    ClaudeMessagesProvider,
    FakeLlmProvider,
    HttpxProviderTransport,
    LlmBudgetLedger,
    LlmProviderCredential,
    LlmProviderTransport,
    LlmScoreRequest,
    LlmUsageEvent,
    LlmUsageRecorder,
    OpenAIResponsesProvider,
    RepositoryLlmUsageRecorder,
    ScoringFailure,
    ScoringQueueResult,
    ScoringRunResult,
    TokenPricing,
    build_scoring_queue,
    check_scoring_failure_gate,
    reconcile_scoring_cost,
    record_provider_cost,
    run_llm_scoring,
    token_pricing_from_env,
)
from app.services.notification_service import (
    AlertCooldownLedger,
    AlertCooldownResult,
    DailyPnlSummary,
    DigestInputs,
    NotificationAlertDecision,
    NotificationDeliveryLedger,
    NotificationDeliveryRecord,
    NotificationSendResult,
    NotificationSettings,
    PositionMovement,
    RenderedDigest,
    alert_allowed_by_cooldown,
    detect_daily_pnl_alert,
    detect_large_movement_alert,
    render_daily_digest,
    send_large_movement_alert,
    send_scheduled_daily_digest,
)
from app.services.polymarket_history_service import (
    POLYMARKET_CTF_EXCHANGE_V2,
    POLYMARKET_GAMMA_BASE_URL,
    POLYMARKET_GAMMA_MARKET_SOURCE,
    POLYMARKET_ORDER_FILLED_V2_SIGNATURE,
    POLYMARKET_POLYGON_ORDER_FILLED_SOURCE,
    PolymarketGammaBackfillError,
    PolymarketGammaMarketBackfiller,
    PolymarketHistoricalImportSummary,
    PolymarketHistoryImporter,
    PolymarketPolygonBackfillError,
    PolymarketPolygonOrderFilledBackfiller,
    decode_order_filled_v2_log,
)
from app.services.risk_engine import (
    AlpacaRiskConfig,
    AlpacaRiskInput,
    LiveOrderGateInput,
    PolymarketRiskConfig,
    PolymarketRiskInput,
    RiskLimitResult,
    check_positive_order_size,
    default_alpaca_risk_config,
    default_polymarket_risk_config,
    evaluate_live_order_gates,
    evaluate_alpaca_risk_limits,
    evaluate_polymarket_risk_limits,
)
from app.services.runtime_status_service import RuntimeCredentialView, RuntimeStatusService
from app.services.traceability_service import (
    ReleaseReadinessCheck,
    ReleaseReadinessSummary,
    TraceabilityScanResult,
    extract_requirement_ids,
    release_readiness_summary,
    requirement_ids_from_requirements,
    scan_traceability,
)
from app.services.wallet_service import (
    CredentialStatus,
    CredentialTarget,
    LocalCredentialResult,
    WalletGenerationRequest,
    WalletGenerationResult,
    build_credential_status,
    check_required_credentials,
    generate_polymarket_wallet,
    load_local_credential,
    resolve_credential_ref,
    validate_unique_credential_refs,
)

__all__ = [
    "ActorContext",
    "ALPACA_BROKER_HISTORY_SOURCE_PREFIX",
    "ALPACA_DATA_BASE_URL",
    "ALPACA_LIVE_TRADING_BASE_URL",
    "ALPACA_PAPER_TRADING_BASE_URL",
    "ALPACA_STOCK_BARS_SOURCE_PREFIX",
    "AlpacaBrokerHistoryBackfiller",
    "AlpacaExecutionRequest",
    "AlpacaExecutionResult",
    "AlpacaHistoricalImportSummary",
    "AlpacaHistoryImportError",
    "AlpacaRiskConfig",
    "AlpacaRiskInput",
    "AlpacaStockHistoryImporter",
    "AlertCooldownLedger",
    "AlertCooldownResult",
    "AuditService",
    "AuthService",
    "ClaudeMessagesProvider",
    "CloudWatchLogSink",
    "ConfigAuthorizationError",
    "ConfigChange",
    "ConfigConflictError",
    "ConfigMutationResult",
    "ConfigPatchOperation",
    "ConfigReloadResult",
    "ConfigSaveResult",
    "ConfigService",
    "ConfigValidationError",
    "DEFAULT_ALPACA_SYMBOL_UNIVERSE",
    "DEFAULT_ALPACA_SYMBOL_PRESETS",
    "DEFAULT_SCANNER_CONFIG",
    "ComparisonGroup",
    "ComparisonDashboardView",
    "ComparisonSummary",
    "CredentialStatus",
    "CredentialTarget",
    "DashboardAccessResult",
    "DashboardShellResult",
    "DashboardStatusResult",
    "DataFreshnessStatus",
    "DailyPnlSummary",
    "DigestInputs",
    "DryRunOrderRequest",
    "ExecutionResult",
    "ExitExecutionRequest",
    "ExitExecutionResult",
    "FakeAlpacaVenueSubmitter",
    "FakeCancelVenue",
    "FakeLlmProvider",
    "FakeSnapshotSource",
    "FakeVenueSubmitter",
    "HttpxProviderTransport",
    "IngestionCheckpoint",
    "IngestionRunResult",
    "IngestionService",
    "KillSwitchCancelResult",
    "KillSwitchActivationResult",
    "KillSwitchService",
    "KillSwitchState",
    "LiveOrderGateInput",
    "LogEmissionResult",
    "LocalCredentialResult",
    "LlmBudgetLedger",
    "LlmProviderCredential",
    "LlmProviderTransport",
    "LlmScoreRequest",
    "LlmUsageEvent",
    "LlmUsageRecorder",
    "MarketDataProviderResult",
    "MutationContextResult",
    "ModelProviderSummary",
    "NotificationAlertDecision",
    "NotificationDeliveryLedger",
    "NotificationDeliveryRecord",
    "NotificationSendResult",
    "NotificationSettings",
    "ObservabilitySnapshot",
    "OpenAIResponsesProvider",
    "OpenOrder",
    "PolymarketExecutionRequest",
    "PerformanceRecord",
    "POLYMARKET_CTF_EXCHANGE_V2",
    "POLYMARKET_GAMMA_BASE_URL",
    "POLYMARKET_GAMMA_MARKET_SOURCE",
    "POLYMARKET_ORDER_FILLED_V2_SIGNATURE",
    "POLYMARKET_POLYGON_ORDER_FILLED_SOURCE",
    "PolymarketRiskConfig",
    "PolymarketRiskInput",
    "PolymarketGammaBackfillError",
    "PolymarketGammaMarketBackfiller",
    "PolymarketHistoricalImportSummary",
    "PolymarketHistoryImporter",
    "PolymarketPolygonBackfillError",
    "PolymarketPolygonOrderFilledBackfiller",
    "PositionMovement",
    "ProviderBackedMarketDataFetcher",
    "decode_order_filled_v2_log",
    "BUILT_IN_ALPACA_PRESETS",
    "RenderedDigest",
    "ReleaseReadinessCheck",
    "ReleaseReadinessSummary",
    "RepositoryLlmUsageRecorder",
    "RiskLimitResult",
    "RuntimeConfigSnapshot",
    "RuntimeCredentialView",
    "RuntimeStatusService",
    "ScoringFailure",
    "ScoringQueueResult",
    "ScoringRunResult",
    "ScannerRunResult",
    "ScannerService",
    "TokenPricing",
    "TraceabilityScanResult",
    "WalletGenerationRequest",
    "WalletGenerationResult",
    "alert_allowed_by_cooldown",
    "build_credential_status",
    "build_comparison_dashboard_view",
    "build_dashboard_shell",
    "build_dashboard_status",
    "build_model_provider_summary",
    "build_scoring_queue",
    "cancel_open_orders_for_kill_switch",
    "check_scoring_failure_gate",
    "check_positive_order_size",
    "check_required_credentials",
    "compare_model_performance",
    "detect_daily_pnl_alert",
    "detect_large_movement_alert",
    "default_config_payload",
    "default_alpaca_risk_config",
    "default_polymarket_risk_config",
    "check_market_data_freshness",
    "execute_dry_run_order",
    "execute_alpaca_order",
    "execute_polymarket_order",
    "execute_exit_order",
    "evaluate_live_order_gates",
    "evaluate_alpaca_risk_limits",
    "evaluate_profit_target_exit",
    "evaluate_polymarket_risk_limits",
    "evaluate_stale_thesis_exit",
    "evaluate_volume_spike_exit",
    "extract_requirement_ids",
    "generate_polymarket_wallet",
    "load_local_credential",
    "mark_comparison_metric_unavailable",
    "reconcile_scoring_cost",
    "record_provider_cost",
    "normalize_symbol_list",
    "resolve_alpaca_symbol_universe",
    "release_readiness_summary",
    "render_wallet_dashboard_status",
    "render_daily_digest",
    "requirement_ids_from_requirements",
    "resolve_credential_ref",
    "resolve_alpaca_account_mode",
    "run_llm_scoring",
    "scan_traceability",
    "scanner_config_from_payload",
    "scanner_run_payload",
    "send_large_movement_alert",
    "send_scheduled_daily_digest",
    "validate_unique_credential_refs",
    "token_pricing_from_env",
]
