"""Domain models and validation helpers.

REQ: REQ-VEN-001, REQ-ALP-001, REQ-ALP-002, REQ-DB-004, REQ-DB-005,
REQ-LLM-003, REQ-STR-007, REQ-EXE-008, REQ-EXE-016, REQ-EXT-001,
REQ-CMP-001, REQ-CMP-003, REQ-OBS-001
"""

from app.domain.models import (
    ComparisonMetric,
    Environment,
    EventPersistenceResult,
    ExitTrigger,
    ExitTriggerType,
    Instrument,
    InstrumentType,
    ModelProvider,
    OrderEvent,
    OrderEventType,
    OrderSide,
    OrderType,
    PositionSnapshot,
    PositionState,
    PositionTransition,
    RiskDecision,
    ScoringOutput,
    StrategySignal,
    StructuredLogEvent,
    TradeDecision,
    Venue,
    calculate_return_to_risk,
    eligible_alpaca_instruments,
    ensure_signals_persisted,
    evaluate_exit_triggers,
    kelly_sized_notional,
    metric_group_key,
    record_order_event,
    redact_metadata,
    supported_polymarket_venues,
    supported_venues,
)

__all__ = [
    "ComparisonMetric",
    "Environment",
    "EventPersistenceResult",
    "ExitTrigger",
    "ExitTriggerType",
    "Instrument",
    "InstrumentType",
    "ModelProvider",
    "OrderEvent",
    "OrderEventType",
    "OrderSide",
    "OrderType",
    "PositionSnapshot",
    "PositionState",
    "PositionTransition",
    "RiskDecision",
    "ScoringOutput",
    "StrategySignal",
    "StructuredLogEvent",
    "TradeDecision",
    "Venue",
    "calculate_return_to_risk",
    "eligible_alpaca_instruments",
    "ensure_signals_persisted",
    "evaluate_exit_triggers",
    "kelly_sized_notional",
    "metric_group_key",
    "record_order_event",
    "redact_metadata",
    "supported_polymarket_venues",
    "supported_venues",
]
